module.exports = {
  preset: 'react-native',
  setupFiles: ['<rootDir>/jest.setup.js'],
  collectCoverage: true,
  coverageReporters: ['html', 'text'],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transformIgnorePatterns: [
    '/node_modules/(?!(@react-native|react-native|@fortawesome/react-native-fontawesome)).*/',
  ],
  setupFilesAfterEnv: ['<rootDir>/__mocks__/globalMock.js'],
  coveragePathIgnorePatterns: [
    '/.eslintrc.js',
    '/App.tsx',
    '/index.js',
    '/jest.config.js',
    '/node_modules/',
    '/.prettierrc.js',
    '/src/constants',
    '/src/reducer',
    '/src/actions',
    '/src/routes/index.tsx',
    '/src/routes/RootNavigation.tsx',
    '/src/services',
    '/src/utils',
    '/src/utils/index.tsx',
    '/styles.tsx',
    'sorter.js',
    'block-navigation.js',
    'prettify.js',
    '/src/components/Text',
    '/src/components/Header',
    '/src/components/FilterList',
    '/src/components/HeaderSearch',
    '/src/components/Input',
    '/src/components/MarketItem',
    '/src/components/MarketList',
    '/src/components/MarketItem',
  ],
  testPathIgnorePatterns: [
    '/.eslintrc.js',
    '/App.tsx',
    '/index.js',
    '/index.tsx',
    '/jest.config.js',
    '/node_modules/',
    '/src/constants',
    '/src/reducer',
    '/src/actions',
    '/src/routes/index.tsx',
    '/src/routes/RootNavigation.tsx',
    '/src/services',
    '/src/utils',
    '/src/utils/index.tsx',
    '/styles.tsx',
    'sorter.js',
    'block-navigation.js',
    'prettify.js',
    '/src/components/Text',
    '/src/components/Header',
    '/src/components/FilterList',
    '/src/components/HeaderSearch',
    '/src/components/Input',
    '/src/components/MarketItem',
    '/src/components/MarketList',
    '/src/components/MarketItem',
  ],
};
