export const DUMMY_MARKET_DATA: SupportedCurrency[] = [
  {
    color: '',
    currencyGroup: '',
    currencySymbol: '',
    decimal_point: 0,
    listingDate: '',
    logo: '',
    name: '',
  },
  {
    color: '',
    currencyGroup: '',
    currencySymbol: '',
    decimal_point: 0,
    listingDate: '',
    logo: '',
    name: '',
  },
  {
    color: '',
    currencyGroup: '',
    currencySymbol: '',
    decimal_point: 0,
    listingDate: '',
    logo: '',
    name: '',
  },
  {
    color: '',
    currencyGroup: '',
    currencySymbol: '',
    decimal_point: 0,
    listingDate: '',
    logo: '',
    name: '',
  },
  {
    color: '',
    currencyGroup: '',
    currencySymbol: '',
    decimal_point: 0,
    listingDate: '',
    logo: '',
    name: '',
  },
  {
    color: '',
    currencyGroup: '',
    currencySymbol: '',
    decimal_point: 0,
    listingDate: '',
    logo: '',
    name: '',
  },
  {
    color: '',
    currencyGroup: '',
    currencySymbol: '',
    decimal_point: 0,
    listingDate: '',
    logo: '',
    name: '',
  },
];
